title = "Amtrak's Acela: Saturday Southbound"
heading = "Acela: Saturday Southbound"
aria_label = "Acela Saturday Southbound"
reference_date = "20260905"
# This timetable gets split programmatically
max_columns_per_page = 10
landscape = false
key_on_right = false
key_baggage = true
key_d = true
key_r = true
for_rpa = true

