title = "Amtrak's Acela: Saturday Southbound"
heading = "Acela: Saturday Southbound"
aria_label = "Acela Saturday Southbound"
reference_date = "20250823"
# This timetable gets split programmatically
max_columns_per_page = 9
landscape = true
key_on_right = true
key_baggage = true
key_d = true
key_r = true
for_rpa = true

