title = "Amtrak's Acela: Sunday Southbound"
heading = "Acela: Sunday Southbound"
aria_label = "Acela Sunday Southbound"
reference_date = "20260906"
# This timetable gets split programmatically
max_columns_per_page = 10
landscape = false
key_on_right = false
key_baggage = true
key_d = true
key_r = true
for_rpa = true

