title = "Amtrak's Acela: Saturday Northbound"
heading = "Acela: Saturday Northbound"
aria_label = "Acela Saturday Northbound"
reference_date = "20250823"
# This timetable gets split programmatically
max_columns_per_page = 9
landscape = true
key_on_right = true
key_baggage = true
key_d = true
key_r = true
for_rpa = true

