title = "Auto Train"
heading = "Auto Train"
aria_label = "Auto Train"
reference_date = "20241117"
top_text = "The Auto Train carries passengers only with a motor vehicle.<br><br>Auto Train has specific times for vehicle check-in. For details and requirements, see <a href=\"https://www.amtrak.com/route-content/auto-train-boarding-and-vehicle-requirements.html\">https://www.amtrak.com/route-content/auto-train-boarding-and-vehicle-requirements.html</a>."
for_rpa = true
