title = "Capitol Corridor Weekday Eastbound"
heading = "Capitol Corridor: Weekday Eastbound"
aria_label = "Capitol Corridor Weekday Eastbound"
landscape = true
reference_date = "20241001"
key_bus = true
use_bus_icon_in_cells = true
key_baggage = true
key_d = true
for_rpa = true
