title = "Capitol Corridor Weekend Eastbound"
heading = "Capitol Corridor: Weekend Eastbound"
aria_label = "Capitol Corridor Weekend Eastbound"
programmers_warning = "Not revised because of ghost buses and real buses which aren't in GTFS."
landscape = true
reference_date = "20241001"
key_bus = true
use_bus_icon_in_cells = true
key_baggage = true
key_d = true
for_rpa = true
