title = "Cascades Northbound"
heading = "Cascades: Northbound"
aria_label = "Cascades Northbound"
reference_date = "20241001"
programmers_warning = "Oregon Point buses missing.  Coast Starlight duplicate timetable problems."
key_baggage = true
for_rpa = true
key_bus = true
use_bus_icon_in_cells = true
