title = "Rochester, MN Timetable"
heading = "Thruway Bus Connection: Rochester, MN"
aria_label = "Rochester MN Bus"
reference_date = "20241001"
top_text = "Groome Transportation buses provide connections from Rochester to St. Paul-Minneapolis and points west on the Empire Builder, as well as additional frequencies between LaCrosse, WI; Winona, MN; and St. Paul-Minneapolis."
for_rpa = true
