title = "Pacific Surfliner Northbound"
heading = "Pacific Surliner: Northbound"
aria_label = "Pacific Surfliner Northbound"
landscape = true
reference_date = "20241001"
key_baggage = true
key_r = true
for_rpa = true
