title = "Galesburg and Quincy Timetable"
heading = "Galesburg and Quincy"
agency_css_class = "amtrak-to-css"
aria_label = "Galesburg Quincy"
reference_date = "20241001"
bottom_text = "<b>Amtrak does not carry local passengers</b> between Chicago, La Grange Road, and Naperville unless connecting to other Amtrak trains."
key_baggage = true
key_r = true
key_d = true
for_rpa = true
