title = "Richmond & Hampton Roads Timetable - Weekend Southbound"
heading = "Richmond & Hampton Roads - Weekend Southbound"
amtrak_css_class = "amtrak-to-css"
aria_label = "Richmond Weekend Southbound"
reference_date = "20250112"
key_baggage = true
key_r = true
compress_credits = true
for_rpa = true
