title = "San Joaquins Southbound"
heading = "San Joaquins: Southbound"
aria_label = "San Joaquins Southbound"
landscape = true
reference_date = "20241001"
key_baggage = true
key_r = true
key_d = true
key_l = true
for_rpa = true
