title = "Silver Service/Palmetto Timetable page 1"
heading = "Silver Service & Palmetto - Carolinas & Georgia"
aria_label = "Silver Service page 1"
reference_date = "20241216"
bottom_text = "<p class=\"mile-header-text\">Mileage note 1 - Via Raleigh, Columbia and Tampa (Trains 79, 80, 91, 92)<br>Mileage note 2 - Via Fayetteville and Charleston (Trains 89, 90, 97, 98)</p><p class=\"top-text\"><b>See next page for services south of Savannah, Georgia to Florida.</b></p>"
programmers_note = "Using dwell_secs_cutoff of 6 minutes to shorten timetable"
dwell_secs_cutoff = 360
landscape = true
key_on_right = false
key_baggage = true
key_d = true
key_r = true
for_rpa = false
