title = "Winter Park Express Timetable"
heading = "Winter Park Express"
aria_label = "Winter Park Express"
reference_date = "20260929"
for_rpa = true
top_text = "The Winter Park Express ski train will run Fridays, Saturdays and Sundays from December 19 through January 4. Expanded service will run Thursdays, Fridays, Saturdays and Sundays from January 8 through March 29, 2026."
programmers_warning = ""
